function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 04-Feb-2019 15:19:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'ZDataSource','','MarkerFaceColor',[1 0 0],'MarkerSize',18,...
    'Marker','diamond',...
    'LineStyle','--');

box(axes1,'on');
